name: Now Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '!web/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deployment
        run: "now web --prod"
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
