name: Now Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '!web/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deployment
        uses: actions/zeit-now@1.0.0
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: "web/ --prod"
